- name: "Ansible para configurar VM"
  hosts: aws_ec2
  become: true
  gather_facts: yes

  tasks:
    - name: Linux - Atualizando todos os pacotes
      package:
        name: '*'
        state: latest

    - name: Repositorio Ansible
      apt_repository:
        repo: ppa:ansible/ansible
      
    - name: Verifique se uma lista de pacotes para instalar
      package:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - python3
        - python3-pip
        - python-pip
        - lvm2
        - ansible
        - software-properties-common

    - name: Verifica pacotes essenciais do python
      pip:
        name: "{{ packages }}"
      vars:
        packages:
        - boto
        - boto3
    
    - name: Download required roles docker (desktop local)
      local_action: command ansible-galaxy install nickjj.docker 
      become: false

    - name: Download required roles java
      local_action: command ansible-galaxy install geerlingguy.java 
      become: false

    - name: Download required roles jenkins
      local_action: command ansible-galaxy install geerlingguy.jenkins 
      become: false
