- name: "Ansible para configurar VM"
  hosts: local
  become: true
  gather_facts: yes

  tasks:
    - name: 1 - Linux - Atualizando todos os pacotes
      package:
        name: '*'
        state: latest

    - name: 2 - Verifique se uma lista de pacotes está instalada
      package:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - python3
        - python3-pip
        - python-pip
        - lvm2

    - name: 3 - Verifica pacotes essenciais do python
      pip:
        name: "{{ packages }}"
      vars:
        packages:
        - boto
        - boto3
