- name: Instalar Jenkins em VM
  hosts: local
  become: true
  gather_facts: yes

  vars:
    jenkins_hostname: "127.0.0.1"
    jenkins_port: 8080
    jenkins_java_options: "-Djava.net.preferIPv4Stack=true -Djenkins.install.runSetupWizard=false"
    jenkins_include_secrets: true

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins